### ISSUE TITLE
Data storage

### ISSUE THREAD

**Issue by aliciacanipe** [spacetelescope/nircam_jdox#9]
We need to figure out what we want to do about data used to generate JDox figures. Some of the files are small text files. Several are used across different pages and for multiple figures. Some data, like throughputs or sensitivities, are in FITS files. 

Right now we have a "data" directory on GitHub for the smaller text files. I temporarily created a "data" directory on the server to host the FITS files (/ifs/jwst/wit/witserv/data7/nrc/JDoxPlots/data).

**Comment by bhilbert4** [comment]
I know that Matt Bourque doesn't like any fits files at all to be on github. I'll have to ask him why that is.

One option (which would add a little more work) would be to use Box. I'm starting to do this for Mirage because the files are too big for github, but in this case we could then still claim that the files are being version controlled. It would then just take a couple additional lines in each notebook to download the appropriate file and read it in.

**Comment by aliciacanipe** [comment]
Yeah, I was originally thinking it wasn't too big of an issue because the files I was using at the time were text files, but then I remembered the transmission files are FITS. I suppose Box would be the best, since that's generally what everyone eventually decides to use when it comes to FITS files.

**Comment by bhilbert4** [comment]
This describes the way to put things on Box. Links are annoying in that there is no programmatic way to get them, so they all have to be hard coded into the notebook.
https://github.com/spacetelescope/style-guides/blob/master/guides/where-to-put-your-data.md

**Comment by aliciacanipe** [comment]
Oh okay, I clearly didn't look closely enough at the style guides repo. I didn't know they had data guides too. We have a NIRCam Box already (ST-INS-NIRCAM, https://stsci.app.box.com/folder/3445993368), should we add a jdox directory and dump the files there? I see a filter_throughputs folder.

**Comment by bhilbert4** [comment]
Yeah, I think a JDox folder makes sense. Should we keep only fits in there, or everything?

**Comment by aliciacanipe** [comment]
I think I would rather keep all the data in one location. If you agree, I can move the files in the "data" directories to a Box folder. Then I'll update the notebooks.

**Comment by bhilbert4** [comment]
Makes sense. I like the idea of having everything in one place

**Comment by aliciacanipe** [comment]
I didn't mean to

**Comment by aliciacanipe** [comment]
Oh geez. I'm sorry. I just hit all the wrong buttons. I meant to say "I'm going to close this now that we have a Box folder for the JDox data here: https://stsci.box.com/s/z38329tz8q9748l3ginnct9ng9qv9g4w
